spring:
  application:
    name: openapi-gateway
  cloud:
    gateway:
      http-client:
        connect-timeout: 10000
        response-timeout: 7s
      routes:
        - id: first-service
          uri: "http://localhost:8180/"
          predicates:
            - Path=/first/* , /v3/api-docs/first
          filters:
            - name: CircuitBreaker
              args:
                name: firstBreaker
                fallbackUri: forward:/fb/first/
        - id: second-service
          uri: "http://localhost:8280/"
          predicates:
            - Path=/second/* , /v3/api-docs/second
          filters:
            - name: CircuitBreaker
              args:
                name: secondBreaker
                fallbackUri: forward:/fb/second/
    discovery:
      enabled: true

resilience4j:
  time limiter:
    configs:
      default:
        timeoutDuration: 7000
        cancelRunningFuture: true

logging:
  level:
    org:
      springframework:
        cloud.gateway: DEBUG
        http.server.reactive: DEBUG
        web.reactive: DEBUG
